### PR TITLE
ARROW-8797: Add golden files to support ipc between different endians

### PR DESCRIPTION
**Pull request by kiszk**
Add golden files for big and little endians for https://github.com/apache/arrow/pull/7507 based on @wesm 's [suggestion](https://github.com/apache/arrow/pull/7507#issuecomment-657282736).

### CODE REVIEW

**Comment by kiszk** [comment]
cc @wesm

**Comment by wesm** [comment]
Nit: do we want maybe to put these files in directories like

- `integration/1.0.0-littleendian`
- `integration/1.0.0-bigendian`

? Is there a script somewhere for generating these files? I think I have asked this in the past and I'm still not sure the answer

**Comment by kiszk** [comment]
Should I put a set of scripts into `integration/1.0.0-littleendian` and `integration/1.0.0-bigendian`? (Same set for both endian).   
Or, should I put the set here as a comment of this PR?

**Comment by wesm** [comment]
Probably the script should be a part of apache/arrow and be used to generate a set of golden files at a point in time for a particular build, maybe it could be a part of the `archery` tool or simply a bash script would be OK too

**Comment by kiszk** [comment]
I see. I will add a script to https://github.com/apache/arrow/pull/7507

**Pull request merged**
