### PR TITLE
update int64 columns to use string values

### PR DESCRIPTION
**Pull request by emkornfield**
@wesm I hand edited (with vim macro) and then verified it can be parsed with python (I didn't rerun integration tests.  Is there an easy way to do that?  Also it looks like the only int64 usage I could find is with primitives (the file edited and zero batch test cases).

### CODE REVIEW

**Comment by wesm** [comment]
It's possible this dictionary test uses strings too https://github.com/apache/arrow/blob/master/dev/archery/archery/integration/datagen.py#L1426

**Comment by emkornfield** [comment]
Thanks update the dictionary.json.gz as well.

**Comment by pitrou** [comment]
Can you explain the changes done?

**Comment by emkornfield** [comment]
Changes:
1. Gunzip affected file
2. Find values related to int64/uint64 columns and put them in quotes.
3. Gzip the files

**Comment by pitrou** [comment]
I thanks. I hadn't notice those were the JSON files.

**Comment by wesm** [comment]
@emkornfield @pitrou I'll try to test these locally

**Comment by wesm** [comment]
Ah the interval and datetime tests also have the issue

https://gist.github.com/wesm/bf650d27557e90b4833054ab01783623

I'll try to fix them locally

**Comment by wesm** [comment]
OK, passing now (fun times with emacs regexp-replace).

https://gist.github.com/wesm/b7ed6934ef7753c2087919156c751bf4

+1

**Pull request merged**
