### PR TITLE
ARROW-6102: Add partitioned CSV example

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by wesm** [comment]
Wouldn't it be better to generate an example?

**Comment by andygrove** [comment]
My thinking was that I could run queries against the single file and the partitioned version and check that the results match

**Comment by andygrove** [comment]
Oh, you mean generate a partitioned version directly from the Rust unit test? I guess that could work.

**Comment by wesm** [comment]
Yeah, that's what we do in Python for our partitioned Parquet tests, for examle

**Comment by andygrove** [comment]
ok thanks @wesm I will do that ... works better for testing different number of partitions too

**Pull request closed without merging**
