### PR TITLE
ARROW-11666: Add golden files for decimal256

### PR DESCRIPTION
**Pull request by kiszk**
This PR adds golden files for decimal256 in big and little endians.

### CODE REVIEW

**Comment by kiszk** [comment]
@pitrou Could you please review this? It works well on my local machine.

**Comment by pitrou** [comment]
Thanks. Can you also remove the "large batch" files in the endian directories? They are heavy to run and don't bring anything IMHO.

**Comment by kiszk** [comment]
Sure, done

**Review by pitrou — APPROVED** [review]
+1, thank you @kiszk

**Comment by pitrou** [comment]
Now you need to update the testing submodule in the Arrow main repo :-)

**Pull request merged**
