### PR TITLE
ARROW-5399: [Testing] Add Rust IPC files

### PR DESCRIPTION
**Pull request by nevi-me**
This adds the files used in ARROW-5181, and the script that generated them,

### CODE REVIEW

**Comment by emkornfield** [comment]
@nevi-me is there anyway rust could use the files already checked in under https://github.com/apache/arrow-testing/tree/master/data/arrow-ipc/integration/0.14.1 instead of these?  These were generated by the integration testing script.  If Rust can read them, it is probably a good indication it is close to being able to be part of the integration tests.  I plan on checking in a new batch after 0.15.0 is released.

**Comment by nevi-me** [comment]
Hi @emkornfield, I think I should be able to. Let me try with a few of them and revert back to you.

**Comment by nevi-me** [comment]
The downside for now is that we don't support generating JSON outputs from record batches, which seems to be required for comparing against the `json.gz` files in the folder. Let me see what I can do though.

**Comment by emkornfield** [comment]
Yeah, there would be more work to actually be part of the integration test, but you I think most of the json files are fairly small, so they could potentially be copied into whatever native RUST you need in the short term and at some point the functionality to read/write can be added later.

**Comment by nevi-me** [comment]
We already generate a JSON representation of the schema, what's missing is the record batch. I think better would be for me to work on the record batch -> json first, and abandon this PR like you suggest.

The Arrow IPC work will eventually need integration testing anyways 😊

**Comment by wesm** [comment]
Ideally a testing corpus would be generated on the fly rather than checking in the files, but I can understand that this might make things easier for developers. 

Note that these files might be using the pre-0.15 message format, do you want to wait until after 0.15.0 is released, or use a dev version to generate the test files?

**Comment by nevi-me** [comment]
I'll wait for 0.15, I think I'll focus on some ground-work to get us ready for integration testing. I've got my spare time back now, so I'll have enough capacity to complete Rust IPC and integration by 1.0.0.

Thanks Micah and Wes

**Pull request closed without merging**
