### PR TITLE
Add IPC fuzz regression file

### PR DESCRIPTION
**Pull request by pitrou**
Add fuzz regression file for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71200

The fix is tracked in https://github.com/apache/arrow/issues/43885

### CODE REVIEW

**Comment by mapleFU** [comment]
Do we need a gh issue?

**Comment by pitrou** [comment]
I opened https://github.com/apache/arrow/issues/43885 for the fix, but we can associate this PR with the issue as well.

**Comment by mapleFU** [comment]
How can I reproduce the problem? Just read this file?

**Comment by pitrou** [comment]
You must first create a fuzzing build: https://arrow.apache.org/docs/developers/cpp/fuzzing.html
Then you can call `arrow-ipc-stream-fuzz <name of file>`.

**Comment by pitrou** [comment]
By the way, do you want to have access to OSS-Fuzz?

**Comment by mapleFU** [comment]
```C++
TEST(ReadFile, XXX) {
  auto read_options = IpcReadOptions::Defaults();
  ASSERT_OK_AND_ASSIGN(auto test_file, io::ReadableFile::Open("clusterfuzz-testcase-minimized-arrow-ipc-stream-fuzz-6234073570279424"));
  ASSERT_OK_AND_ASSIGN(auto reader,
                       RecordBatchStreamReader::Open(test_file, read_options));
  ASSERT_OK_AND_ASSIGN(auto record_batches, reader->ToRecordBatches());
  for (const auto& batch : record_batches) {
    std::cout << batch->num_rows() << std::endl;
  }
}
```

returns:

```

**Review by mapleFU — APPROVED** [review]

**Comment by mapleFU** [comment]
> By the way, do you want to have access to OSS-Fuzz?

Aha, I would like to

**Comment by pitrou** [comment]
> > By the way, do you want to have access to OSS-Fuzz?
> 
> Aha, I would like to

Ok, you need a Google or GMail address that we can add to https://github.com/google/oss-fuzz/blob/master/projects/arrow/project.yaml

**Comment by mapleFU** [comment]
Added here: https://github.com/google/oss-fuzz/pull/12425

**Pull request merged**
